---
swagger: "2.0"
info:
  description: "for PHD"
  version: "1.0.0"
  title: "PHD"
  termsOfService: ""
  contact:
    name: "Developer Gavin"
    email: "gavin19950511@gmail.com"
  license:
    name: "Apache 2.0"
host: "localhost:3080"
basePath: "/PHD"
tags:
- name: "member"
  description: "user"
- name: "step"
  description: "Step"
schemes:
- "http"
paths:
  /logintest:
    get:
      tags:
      - "business"
      summary: ""
      description: ""
      operationId: "logintestGET"
      produces:
      - "application/json"
      parameters:
      - name: "account"
        in: "query"
        description: "account"
        required: true
        type: "string"
      - name: "pws"
        in: "query"
        description: "pws"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/member"
      x-swagger-router-controller: "Business"
  /submembers:
    get:
      tags:
      - "business"
      summary: ""
      description: ""
      operationId: "submembersGET"
      produces:
      - "application/json"
      parameters:
      - name: "mid"
        in: "query"
        description: "host's mid"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/submembers"
      x-swagger-router-controller: "Business"
  /submember:
    get:
      tags:
      - "business"
      summary: ""
      description: ""
      operationId: "submemberGET"
      produces:
      - "application/json"
      parameters:
      - name: "mid"
        in: "query"
        description: " mid"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/submembers"
      x-swagger-router-controller: "Business"
  /member:
    get:
      tags:
      - "member"
      summary: "return the members who meet to the filter."
      description: ""
      operationId: "memberGET"
      parameters:
      - name: "mid"
        in: "query"
        required: false
        type: "string"
        description: "1,2,3,4,5"
      - name: "name"
        in: "query"
        required: false
        type: "string"
        description: "Tony,Theta,Tib"
      - name: "group"
        in: "query"
        required: false
        type: "string"
        description: "NCU_NLT1,NCU_NLT2,NCU_NLT3,NCU_NLT4"
      - name: "permission"
        in: "query"
        required: false
        type: "string"
        enum:
        - "user"
        - "admin"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/member"
      x-swagger-router-controller: "Member"
    post:
      tags:
      - "member"
      summary: "new a member."
      description: ""
      operationId: "memberPOST"
      parameters:
      - in: "body"
        name: "member"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/member"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Member"
    put:
      tags:
      - "member"
      summary: "update the member's data."
      description: ""
      operationId: "memberPUT"
      parameters:
      - in: "body"
        name: "member"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/member"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Member"
    delete:
      tags:
      - "member"
      summary: "delete a member."
      description: ""
      operationId: "memberDELETE"
      parameters:
      - name: "mid"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Member"
  /step:
    get:
      tags:
      - "step"
      summary: "return the members who meet to the filter."
      description: ""
      operationId: "stepGET"
      parameters:
      - name: "sid"
        in: "query"
        description: "1,2,3,4"
        required: false
        type: "string"
      - name: "title"
        in: "query"
        description: "Tony,Tom,"
        required: false
        type: "string"
      - name: "group"
        in: "query"
        description: "NCU_NLT1,NCU_NLT2"
        required: false
        type: "string"
      - name: "submid"
        in: "query"
        description: "1,2,3,4"
        required: false
        type: "string"
      - name: "adminmid"
        in: "query"
        description: "1,2,3,4"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/step"
      x-swagger-router-controller: "Step"
    post:
      tags:
      - "step"
      summary: "new a step to the submember."
      description: ""
      operationId: "stepPOST"
      parameters:
      - in: "body"
        name: "member"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/step"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Step"
    put:
      tags:
      - "step"
      summary: "update the member's a step."
      description: ""
      operationId: "stepPUT"
      parameters:
      - in: "body"
        name: "step"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/step"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Step"
    delete:
      tags:
      - "step"
      summary: "delete a step."
      description: ""
      operationId: "stepDELETE"
      parameters:
      - name: "sid"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Step"
definitions:
  step:
    type: "object"
    required:
    - "group"
    - "sid"
    - "title"
    properties:
      sid:
        type: "string"
      group:
        type: "string"
      title:
        type: "string"
      deadline:
        type: "string"
      log:
        type: "string"
      status:
        type: "integer"
      description:
        type: "string"
      submid:
        type: "string"
      adminmid:
        type: "string"
    example:
      log: "no log"
      description: "description"
      title: "title"
      deadline: "1995-05-11"
      sid: "NULL"
      group: "group"
      status: -1
      submid: "0"
      adminmid: "0"
  member:
    type: "object"
    required:
    - "account"
    - "group"
    - "name"
    - "pws"
    properties:
      mid:
        type: "string"
      account:
        type: "string"
      pws:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      group:
        type: "string"
      permission:
        type: "string"

    example:
      hidden: false
      alert: true
      name: "name"
      mid: "NULL"
      description: "{\"入學年\":\"2019-02-01\",\"指導老師\":\"test\"}"
      permission: "user"
      pws: "pws"
      account: "account"
      group: "group"
  submember:
    allOf:
      - $ref: '#/definitions/member'
    properties:
      steps:
        type: array
        items:
          $ref: '#/definitions/step'


  submembers:
    properties:
      members:
        type: "array"
        items:
          $ref: "#/definitions/submember"
    example:
      members:
      - hidden: true
        alert: true
        name: "name"
        mid: "mid"
        description: "description"
        permission: "permission"
        pws: "pws"
        steps:
        - log: "log"
          description: "description"
          title: "title"
          deadline: "deadline"
          sid: "sid"
          group: "group"
          status: true
        - log: "log"
          description: "description"
          title: "title"
          deadline: "deadline"
          sid: "sid"
          group: "group"
          status: true
        account: "account"
        group: "group"
      - hidden: true
        alert: true
        name: "name"
        mid: "mid"
        description: "description"
        permission: "permission"
        pws: "pws"
        steps:
        - log: "log"
          description: "description"
          title: "title"
          deadline: "deadline"
          sid: "sid"
          group: "group"
          status: true
        - log: "log"
          description: "description"
          title: "title"
          deadline: "deadline"
          sid: "sid"
          group: "group"
          status: true
        account: "account"
        group: "group"
